### ISSUE TITLE
default app not work ...

### ISSUE THREAD

**Issue by mydearxym** [tomitrescak/Meteor-Boilerplate-Webpack-Mantra-Typescript#2]
hi @tomitrescak 
i try your project but seems not work 

http://localhost:3000/todo

![image](https://cloud.githubusercontent.com/assets/6184465/12536527/e83805ac-c2e2-11e5-9357-888ca621a5b8.png)

http://localhost:3000/post/
![image](https://cloud.githubusercontent.com/assets/6184465/12536538/18ef8cd8-c2e3-11e5-94d9-879609d537ec.png)

**Comment by tomitrescak** [comment]
Sorry about that. All works now .. silly errors ;( Thanks for reporting!
